#!/bin/bash
# arguments: [ ceylon executable ] [ repository ]
failed=0
total=0
for dir in *; do
    ! [[ -d "$dir" ]] && continue
    cd "$dir"
    "${1:-ceylon}" run --rep="${2:-+USER}" --rep=../../modules ceylon.formatter/1.2.3 $(<args)
    if diff <(tree result-expected | sed '1s/expected/actual/') <(tree result-actual); then
        # clean up, unless it’s a symlink
        ! [[ -L result-actual ]] && rm -r result-actual
    else
        # don’t clean up, we might want to investigate that
        # but record the failure
        ((failed++))
    fi
    ((total++))
    cd ..
done
((failed == 0)) && tput -T "${TERM:-mach}" setaf 2 || tput -T "${TERM:-mach}" setaf 1
echo "$total total, $((total-failed)) success, $failed failed$(tput -T "${TERM:-mach}" sgr0)"
exit $failed
